/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuccessIndexRouteImport } from './routes/success/index'
import { Route as QuestionnaireIndexRouteImport } from './routes/questionnaire/index'
import { Route as PredictVideoIndexRouteImport } from './routes/predict-video/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as QuestionnaireSegmentedIndexRouteImport } from './routes/questionnaire/segmented/index'
import { Route as PredictionResponseIdIndexRouteImport } from './routes/prediction/$responseId/index'
import { Route as AdminVideoPredictionsIndexRouteImport } from './routes/admin/video-predictions/index'
import { Route as AdminResponsesIndexRouteImport } from './routes/admin/responses/index'
import { Route as AdminQuestionnairesIndexRouteImport } from './routes/admin/questionnaires/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as PredictVideoResultPredictionIdRouteImport } from './routes/predict-video/result/$predictionId'
import { Route as ApiVideoSplatRouteImport } from './routes/api/video/$'
import { Route as AdminVideoPredictionsPredictionIdRouteImport } from './routes/admin/video-predictions/$predictionId'
import { Route as AdminResponsesResponseIdIndexRouteImport } from './routes/admin/responses/$responseId/index'
import { Route as AdminQuestionnairesQuestionnaireIdIndexRouteImport } from './routes/admin/questionnaires/$questionnaireId/index'
import { Route as ApiUploadSegmentedInitRouteImport } from './routes/api/upload/segmented/init'
import { Route as ApiUploadSegmentedFinalizeRouteImport } from './routes/api/upload/segmented/finalize'
import { Route as ApiUploadSegmentedChunkRouteImport } from './routes/api/upload/segmented/chunk'
import { Route as ApiUploadSegmentedUploadIdRouteImport } from './routes/api/upload/segmented/$uploadId'
import { Route as AdminQuestionnairesQuestionnaireIdQuestionIdIndexRouteImport } from './routes/admin/questionnaires/$questionnaireId/$questionId/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessIndexRoute = SuccessIndexRouteImport.update({
  id: '/success/',
  path: '/success/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireIndexRoute = QuestionnaireIndexRouteImport.update({
  id: '/questionnaire/',
  path: '/questionnaire/',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictVideoIndexRoute = PredictVideoIndexRouteImport.update({
  id: '/predict-video/',
  path: '/predict-video/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const QuestionnaireSegmentedIndexRoute =
  QuestionnaireSegmentedIndexRouteImport.update({
    id: '/questionnaire/segmented/',
    path: '/questionnaire/segmented/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PredictionResponseIdIndexRoute =
  PredictionResponseIdIndexRouteImport.update({
    id: '/prediction/$responseId/',
    path: '/prediction/$responseId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminVideoPredictionsIndexRoute =
  AdminVideoPredictionsIndexRouteImport.update({
    id: '/video-predictions/',
    path: '/video-predictions/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminResponsesIndexRoute = AdminResponsesIndexRouteImport.update({
  id: '/responses/',
  path: '/responses/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQuestionnairesIndexRoute =
  AdminQuestionnairesIndexRouteImport.update({
    id: '/questionnaires/',
    path: '/questionnaires/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PredictVideoResultPredictionIdRoute =
  PredictVideoResultPredictionIdRouteImport.update({
    id: '/predict-video/result/$predictionId',
    path: '/predict-video/result/$predictionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiVideoSplatRoute = ApiVideoSplatRouteImport.update({
  id: '/api/video/$',
  path: '/api/video/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideoPredictionsPredictionIdRoute =
  AdminVideoPredictionsPredictionIdRouteImport.update({
    id: '/video-predictions/$predictionId',
    path: '/video-predictions/$predictionId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminResponsesResponseIdIndexRoute =
  AdminResponsesResponseIdIndexRouteImport.update({
    id: '/responses/$responseId/',
    path: '/responses/$responseId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminQuestionnairesQuestionnaireIdIndexRoute =
  AdminQuestionnairesQuestionnaireIdIndexRouteImport.update({
    id: '/questionnaires/$questionnaireId/',
    path: '/questionnaires/$questionnaireId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const ApiUploadSegmentedInitRoute = ApiUploadSegmentedInitRouteImport.update({
  id: '/api/upload/segmented/init',
  path: '/api/upload/segmented/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadSegmentedFinalizeRoute =
  ApiUploadSegmentedFinalizeRouteImport.update({
    id: '/api/upload/segmented/finalize',
    path: '/api/upload/segmented/finalize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadSegmentedChunkRoute = ApiUploadSegmentedChunkRouteImport.update({
  id: '/api/upload/segmented/chunk',
  path: '/api/upload/segmented/chunk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadSegmentedUploadIdRoute =
  ApiUploadSegmentedUploadIdRouteImport.update({
    id: '/api/upload/segmented/$uploadId',
    path: '/api/upload/segmented/$uploadId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute =
  AdminQuestionnairesQuestionnaireIdQuestionIdIndexRouteImport.update({
    id: '/questionnaires/$questionnaireId/$questionId/',
    path: '/questionnaires/$questionnaireId/$questionId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/admin/': typeof AdminIndexRoute
  '/predict-video/': typeof PredictVideoIndexRoute
  '/questionnaire/': typeof QuestionnaireIndexRoute
  '/success/': typeof SuccessIndexRoute
  '/admin/video-predictions/$predictionId': typeof AdminVideoPredictionsPredictionIdRoute
  '/api/video/$': typeof ApiVideoSplatRoute
  '/predict-video/result/$predictionId': typeof PredictVideoResultPredictionIdRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/questionnaires/': typeof AdminQuestionnairesIndexRoute
  '/admin/responses/': typeof AdminResponsesIndexRoute
  '/admin/video-predictions/': typeof AdminVideoPredictionsIndexRoute
  '/prediction/$responseId/': typeof PredictionResponseIdIndexRoute
  '/questionnaire/segmented/': typeof QuestionnaireSegmentedIndexRoute
  '/api/upload/segmented/$uploadId': typeof ApiUploadSegmentedUploadIdRoute
  '/api/upload/segmented/chunk': typeof ApiUploadSegmentedChunkRoute
  '/api/upload/segmented/finalize': typeof ApiUploadSegmentedFinalizeRoute
  '/api/upload/segmented/init': typeof ApiUploadSegmentedInitRoute
  '/admin/questionnaires/$questionnaireId/': typeof AdminQuestionnairesQuestionnaireIdIndexRoute
  '/admin/responses/$responseId/': typeof AdminResponsesResponseIdIndexRoute
  '/admin/questionnaires/$questionnaireId/$questionId/': typeof AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminIndexRoute
  '/predict-video': typeof PredictVideoIndexRoute
  '/questionnaire': typeof QuestionnaireIndexRoute
  '/success': typeof SuccessIndexRoute
  '/admin/video-predictions/$predictionId': typeof AdminVideoPredictionsPredictionIdRoute
  '/api/video/$': typeof ApiVideoSplatRoute
  '/predict-video/result/$predictionId': typeof PredictVideoResultPredictionIdRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/questionnaires': typeof AdminQuestionnairesIndexRoute
  '/admin/responses': typeof AdminResponsesIndexRoute
  '/admin/video-predictions': typeof AdminVideoPredictionsIndexRoute
  '/prediction/$responseId': typeof PredictionResponseIdIndexRoute
  '/questionnaire/segmented': typeof QuestionnaireSegmentedIndexRoute
  '/api/upload/segmented/$uploadId': typeof ApiUploadSegmentedUploadIdRoute
  '/api/upload/segmented/chunk': typeof ApiUploadSegmentedChunkRoute
  '/api/upload/segmented/finalize': typeof ApiUploadSegmentedFinalizeRoute
  '/api/upload/segmented/init': typeof ApiUploadSegmentedInitRoute
  '/admin/questionnaires/$questionnaireId': typeof AdminQuestionnairesQuestionnaireIdIndexRoute
  '/admin/responses/$responseId': typeof AdminResponsesResponseIdIndexRoute
  '/admin/questionnaires/$questionnaireId/$questionId': typeof AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/admin/': typeof AdminIndexRoute
  '/predict-video/': typeof PredictVideoIndexRoute
  '/questionnaire/': typeof QuestionnaireIndexRoute
  '/success/': typeof SuccessIndexRoute
  '/admin/video-predictions/$predictionId': typeof AdminVideoPredictionsPredictionIdRoute
  '/api/video/$': typeof ApiVideoSplatRoute
  '/predict-video/result/$predictionId': typeof PredictVideoResultPredictionIdRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/questionnaires/': typeof AdminQuestionnairesIndexRoute
  '/admin/responses/': typeof AdminResponsesIndexRoute
  '/admin/video-predictions/': typeof AdminVideoPredictionsIndexRoute
  '/prediction/$responseId/': typeof PredictionResponseIdIndexRoute
  '/questionnaire/segmented/': typeof QuestionnaireSegmentedIndexRoute
  '/api/upload/segmented/$uploadId': typeof ApiUploadSegmentedUploadIdRoute
  '/api/upload/segmented/chunk': typeof ApiUploadSegmentedChunkRoute
  '/api/upload/segmented/finalize': typeof ApiUploadSegmentedFinalizeRoute
  '/api/upload/segmented/init': typeof ApiUploadSegmentedInitRoute
  '/admin/questionnaires/$questionnaireId/': typeof AdminQuestionnairesQuestionnaireIdIndexRoute
  '/admin/responses/$responseId/': typeof AdminResponsesResponseIdIndexRoute
  '/admin/questionnaires/$questionnaireId/$questionId/': typeof AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/logout'
    | '/signup'
    | '/admin/'
    | '/predict-video/'
    | '/questionnaire/'
    | '/success/'
    | '/admin/video-predictions/$predictionId'
    | '/api/video/$'
    | '/predict-video/result/$predictionId'
    | '/admin/dashboard/'
    | '/admin/questionnaires/'
    | '/admin/responses/'
    | '/admin/video-predictions/'
    | '/prediction/$responseId/'
    | '/questionnaire/segmented/'
    | '/api/upload/segmented/$uploadId'
    | '/api/upload/segmented/chunk'
    | '/api/upload/segmented/finalize'
    | '/api/upload/segmented/init'
    | '/admin/questionnaires/$questionnaireId/'
    | '/admin/responses/$responseId/'
    | '/admin/questionnaires/$questionnaireId/$questionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/admin'
    | '/predict-video'
    | '/questionnaire'
    | '/success'
    | '/admin/video-predictions/$predictionId'
    | '/api/video/$'
    | '/predict-video/result/$predictionId'
    | '/admin/dashboard'
    | '/admin/questionnaires'
    | '/admin/responses'
    | '/admin/video-predictions'
    | '/prediction/$responseId'
    | '/questionnaire/segmented'
    | '/api/upload/segmented/$uploadId'
    | '/api/upload/segmented/chunk'
    | '/api/upload/segmented/finalize'
    | '/api/upload/segmented/init'
    | '/admin/questionnaires/$questionnaireId'
    | '/admin/responses/$responseId'
    | '/admin/questionnaires/$questionnaireId/$questionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/logout'
    | '/signup'
    | '/admin/'
    | '/predict-video/'
    | '/questionnaire/'
    | '/success/'
    | '/admin/video-predictions/$predictionId'
    | '/api/video/$'
    | '/predict-video/result/$predictionId'
    | '/admin/dashboard/'
    | '/admin/questionnaires/'
    | '/admin/responses/'
    | '/admin/video-predictions/'
    | '/prediction/$responseId/'
    | '/questionnaire/segmented/'
    | '/api/upload/segmented/$uploadId'
    | '/api/upload/segmented/chunk'
    | '/api/upload/segmented/finalize'
    | '/api/upload/segmented/init'
    | '/admin/questionnaires/$questionnaireId/'
    | '/admin/responses/$responseId/'
    | '/admin/questionnaires/$questionnaireId/$questionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  PredictVideoIndexRoute: typeof PredictVideoIndexRoute
  QuestionnaireIndexRoute: typeof QuestionnaireIndexRoute
  SuccessIndexRoute: typeof SuccessIndexRoute
  ApiVideoSplatRoute: typeof ApiVideoSplatRoute
  PredictVideoResultPredictionIdRoute: typeof PredictVideoResultPredictionIdRoute
  PredictionResponseIdIndexRoute: typeof PredictionResponseIdIndexRoute
  QuestionnaireSegmentedIndexRoute: typeof QuestionnaireSegmentedIndexRoute
  ApiUploadSegmentedUploadIdRoute: typeof ApiUploadSegmentedUploadIdRoute
  ApiUploadSegmentedChunkRoute: typeof ApiUploadSegmentedChunkRoute
  ApiUploadSegmentedFinalizeRoute: typeof ApiUploadSegmentedFinalizeRoute
  ApiUploadSegmentedInitRoute: typeof ApiUploadSegmentedInitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success/': {
      id: '/success/'
      path: '/success'
      fullPath: '/success/'
      preLoaderRoute: typeof SuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire/': {
      id: '/questionnaire/'
      path: '/questionnaire'
      fullPath: '/questionnaire/'
      preLoaderRoute: typeof QuestionnaireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict-video/': {
      id: '/predict-video/'
      path: '/predict-video'
      fullPath: '/predict-video/'
      preLoaderRoute: typeof PredictVideoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/questionnaire/segmented/': {
      id: '/questionnaire/segmented/'
      path: '/questionnaire/segmented'
      fullPath: '/questionnaire/segmented/'
      preLoaderRoute: typeof QuestionnaireSegmentedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction/$responseId/': {
      id: '/prediction/$responseId/'
      path: '/prediction/$responseId'
      fullPath: '/prediction/$responseId/'
      preLoaderRoute: typeof PredictionResponseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/video-predictions/': {
      id: '/admin/video-predictions/'
      path: '/video-predictions'
      fullPath: '/admin/video-predictions/'
      preLoaderRoute: typeof AdminVideoPredictionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/responses/': {
      id: '/admin/responses/'
      path: '/responses'
      fullPath: '/admin/responses/'
      preLoaderRoute: typeof AdminResponsesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/questionnaires/': {
      id: '/admin/questionnaires/'
      path: '/questionnaires'
      fullPath: '/admin/questionnaires/'
      preLoaderRoute: typeof AdminQuestionnairesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/predict-video/result/$predictionId': {
      id: '/predict-video/result/$predictionId'
      path: '/predict-video/result/$predictionId'
      fullPath: '/predict-video/result/$predictionId'
      preLoaderRoute: typeof PredictVideoResultPredictionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video/$': {
      id: '/api/video/$'
      path: '/api/video/$'
      fullPath: '/api/video/$'
      preLoaderRoute: typeof ApiVideoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/video-predictions/$predictionId': {
      id: '/admin/video-predictions/$predictionId'
      path: '/video-predictions/$predictionId'
      fullPath: '/admin/video-predictions/$predictionId'
      preLoaderRoute: typeof AdminVideoPredictionsPredictionIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/responses/$responseId/': {
      id: '/admin/responses/$responseId/'
      path: '/responses/$responseId'
      fullPath: '/admin/responses/$responseId/'
      preLoaderRoute: typeof AdminResponsesResponseIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/questionnaires/$questionnaireId/': {
      id: '/admin/questionnaires/$questionnaireId/'
      path: '/questionnaires/$questionnaireId'
      fullPath: '/admin/questionnaires/$questionnaireId/'
      preLoaderRoute: typeof AdminQuestionnairesQuestionnaireIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/upload/segmented/init': {
      id: '/api/upload/segmented/init'
      path: '/api/upload/segmented/init'
      fullPath: '/api/upload/segmented/init'
      preLoaderRoute: typeof ApiUploadSegmentedInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/segmented/finalize': {
      id: '/api/upload/segmented/finalize'
      path: '/api/upload/segmented/finalize'
      fullPath: '/api/upload/segmented/finalize'
      preLoaderRoute: typeof ApiUploadSegmentedFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/segmented/chunk': {
      id: '/api/upload/segmented/chunk'
      path: '/api/upload/segmented/chunk'
      fullPath: '/api/upload/segmented/chunk'
      preLoaderRoute: typeof ApiUploadSegmentedChunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/segmented/$uploadId': {
      id: '/api/upload/segmented/$uploadId'
      path: '/api/upload/segmented/$uploadId'
      fullPath: '/api/upload/segmented/$uploadId'
      preLoaderRoute: typeof ApiUploadSegmentedUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questionnaires/$questionnaireId/$questionId/': {
      id: '/admin/questionnaires/$questionnaireId/$questionId/'
      path: '/questionnaires/$questionnaireId/$questionId'
      fullPath: '/admin/questionnaires/$questionnaireId/$questionId/'
      preLoaderRoute: typeof AdminQuestionnairesQuestionnaireIdQuestionIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminVideoPredictionsPredictionIdRoute: typeof AdminVideoPredictionsPredictionIdRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminQuestionnairesIndexRoute: typeof AdminQuestionnairesIndexRoute
  AdminResponsesIndexRoute: typeof AdminResponsesIndexRoute
  AdminVideoPredictionsIndexRoute: typeof AdminVideoPredictionsIndexRoute
  AdminQuestionnairesQuestionnaireIdIndexRoute: typeof AdminQuestionnairesQuestionnaireIdIndexRoute
  AdminResponsesResponseIdIndexRoute: typeof AdminResponsesResponseIdIndexRoute
  AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute: typeof AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminVideoPredictionsPredictionIdRoute:
    AdminVideoPredictionsPredictionIdRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminQuestionnairesIndexRoute: AdminQuestionnairesIndexRoute,
  AdminResponsesIndexRoute: AdminResponsesIndexRoute,
  AdminVideoPredictionsIndexRoute: AdminVideoPredictionsIndexRoute,
  AdminQuestionnairesQuestionnaireIdIndexRoute:
    AdminQuestionnairesQuestionnaireIdIndexRoute,
  AdminResponsesResponseIdIndexRoute: AdminResponsesResponseIdIndexRoute,
  AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute:
    AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  PredictVideoIndexRoute: PredictVideoIndexRoute,
  QuestionnaireIndexRoute: QuestionnaireIndexRoute,
  SuccessIndexRoute: SuccessIndexRoute,
  ApiVideoSplatRoute: ApiVideoSplatRoute,
  PredictVideoResultPredictionIdRoute: PredictVideoResultPredictionIdRoute,
  PredictionResponseIdIndexRoute: PredictionResponseIdIndexRoute,
  QuestionnaireSegmentedIndexRoute: QuestionnaireSegmentedIndexRoute,
  ApiUploadSegmentedUploadIdRoute: ApiUploadSegmentedUploadIdRoute,
  ApiUploadSegmentedChunkRoute: ApiUploadSegmentedChunkRoute,
  ApiUploadSegmentedFinalizeRoute: ApiUploadSegmentedFinalizeRoute,
  ApiUploadSegmentedInitRoute: ApiUploadSegmentedInitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
